'use client'

import { useState } from 'react'
import { Loader2, Key, X, Check } from 'lucide-react'
import toast from 'react-hot-toast'

interface Props {
  defaultEmail?: string
  onClose: () => void
}

// Modal shown from the org login page. The user enters the 6-digit code
// generated by the superadmin, plus a new password.
export function PasswordResetModal({ defaultEmail = '', onClose }: Props) {
  const [email, setEmail]       = useState(defaultEmail)
  const [code, setCode]         = useState('')
  const [pw, setPw]             = useState('')
  const [pw2, setPw2]           = useState('')
  const [busy, setBusy]         = useState(false)
  const [done, setDone]         = useState(false)
  const [err, setErr]           = useState('')

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setErr('')
    if (pw !== pw2) { setErr('Passwords do not match'); return }
    if (pw.length < 8) { setErr('Password must be at least 8 characters'); return }
    if (!/^\d{6}$/.test(code)) { setErr('Code must be exactly 6 digits'); return }

    setBusy(true)
    const res = await fetch('/api/auth/use-reset-code', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: email.trim().toLowerCase(), code: code.trim(), newPassword: pw }),
    })
    const data = await res.json()
    if (!res.ok) {
      setErr(data.error || 'Failed to reset password')
      setBusy(false)
      return
    }
    setDone(true)
    setBusy(false)
    toast.success('Password updated — sign in with your new password')
    setTimeout(onClose, 1500)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: 'rgba(15,23,42,0.7)', backdropFilter: 'blur(4px)' }}>
      <div className="w-full max-w-sm rounded-2xl bg-white shadow-xl overflow-hidden">

        <div className="p-5 border-b border-slate-100 flex items-start justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-amber-50 border border-amber-200 flex items-center justify-center">
              <Key size={16} className="text-amber-600" />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-900">Reset password</h2>
              <p className="text-xs text-slate-500 mt-0.5">Use the 6-digit code from your admin</p>
            </div>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-700 p-1 transition">
            <X size={16} />
          </button>
        </div>

        {done ? (
          <div className="p-8 text-center space-y-3">
            <div className="w-12 h-12 mx-auto rounded-full bg-emerald-100 flex items-center justify-center">
              <Check size={20} className="text-emerald-600" />
            </div>
            <p className="text-sm font-semibold text-slate-900">Password updated</p>
            <p className="text-xs text-slate-500">You can now sign in with your new password.</p>
          </div>
        ) : (
          <form onSubmit={handleSubmit} className="p-5 space-y-3">
            <div>
              <label className="block text-xs font-medium text-slate-700 mb-1">Email</label>
              <input type="email" required value={email} onChange={e => setEmail(e.target.value)}
                placeholder="you@example.com"
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-brand-400 focus:border-transparent" />
            </div>
            <div>
              <label className="block text-xs font-medium text-slate-700 mb-1">6-digit reset code</label>
              <input type="text" required value={code} maxLength={6} inputMode="numeric"
                onChange={e => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))}
                placeholder="000000"
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-base font-mono tracking-[0.4em] text-center focus:outline-none focus:ring-2 focus:ring-brand-400 focus:border-transparent" />
            </div>
            <div>
              <label className="block text-xs font-medium text-slate-700 mb-1">New password</label>
              <input type="password" required value={pw} onChange={e => setPw(e.target.value)}
                placeholder="At least 8 characters" minLength={8}
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-brand-400 focus:border-transparent" />
            </div>
            <div>
              <label className="block text-xs font-medium text-slate-700 mb-1">Confirm password</label>
              <input type="password" required value={pw2} onChange={e => setPw2(e.target.value)}
                placeholder="Re-enter password" minLength={8}
                className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-brand-400 focus:border-transparent" />
            </div>

            {err && <p className="text-xs text-red-600 bg-red-50 border border-red-100 rounded-lg px-3 py-2">{err}</p>}

            <button type="submit" disabled={busy}
              className="w-full py-2.5 bg-brand-800 hover:bg-brand-900 text-white rounded-lg text-sm font-bold transition disabled:opacity-60 inline-flex items-center justify-center gap-2">
              {busy && <Loader2 size={14} className="animate-spin" />}
              {busy ? 'Updating…' : 'Reset password'}
            </button>
            <p className="text-[11px] text-slate-400 text-center pt-1">
              Don&apos;t have a code? Ask your admin or contact support.
            </p>
          </form>
        )}
      </div>
    </div>
  )
}
